### ISSUE TITLE
feat(bash): implement script

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-addon-boilerplate#9]
## User Story
As a developer, I need a script to quickly rename plugin constants, text domain, and function name prefixes.

Links:
https://github.com/Charitable/charitable-extension-boilerplate/

**Comment by raftaar1191** [comment]
Here is an example of the plugin boilerplate  that used bash script to change the function name, file name and class name as well 


https://github.com/xwp/wp-foo-bar

**Comment by ravinderk** [comment]
Addon boilerplate revamp and this issue is not relevant, so I am closing this issue.
